#!/usr/bin/env python3
"""
prerender_i18n.py — static per-language prerender (S1)

PROBLEM it solves: the site shipped one URL per page with all 3 languages in
data-en/it/pt attributes, switched client-side. Crawlers only indexed ONE
language, and hreflang pointed every language at the same URL (non-functional).

WHAT it does: reads the editable templates in _src/ (which keep the data-*
attributes) and bakes a STATIC, single-language page for each language:

    _src/reiki.html  ->  reiki.html        (Italian, the bare/default + x-default)
                         en/reiki.html      (English)
                         pt/reiki.html      (Portuguese)

Per output it: bakes data-{lang} into the DOM, strips data-* (clean output),
sets <html lang>, rewrites <title>/description/OG/canonical/hreflang per
language, converts the EN/IT/PT nav toggle from setLang() onclick to real
<a href> links, absolutizes asset paths (so subfolder pages find /shared.css,
/images, ...), lang-prefixes internal page links in the /en and /pt trees,
and injects window.HU_LANG so shared.js does NOT re-switch content at runtime.

Default (bare) language = ITALIAN. English -> /en, Portuguese -> /pt.

Editable source of truth = _src/. The root + en/ + pt/ HTML files are GENERATED
— do not hand-edit them; edit _src/ and re-run this script.

Usage:
  python scripts/prerender_i18n.py                # build all
  python scripts/prerender_i18n.py --only reiki   # build one page (all langs)
"""
import os
import re
import sys
import glob
import json
import warnings
from bs4 import BeautifulSoup, NavigableString
from bs4 import MarkupResemblesLocatorWarning

warnings.simplefilter("ignore", MarkupResemblesLocatorWarning)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "_src")
SITE = "https://holisticunity.app"

LANGS = ["it", "en", "pt"]
DEFAULT_LANG = "it"                  # bare URLs (no prefix) serve this language
LOCALE = {"it": "it_IT", "en": "en_US", "pt": "pt_BR"}
BRAND = "Holistic Unity"

ONLY = None
if "--only" in sys.argv:
    ONLY = sys.argv[sys.argv.index("--only") + 1]

GEN_HEADER = ("<!-- GENERATED by scripts/prerender_i18n.py — DO NOT EDIT. "
              "Edit the template in _src/ and re-run the script. -->")

# Internal page slugs (used to detect links that must be language-prefixed).
PAGE_SLUGS = {
    "", "about", "reiki", "astrology", "ayurveda", "numerology", "human-design",
    "thetahealing", "naturopathy", "family-constellation",
    "systemic-constellation", "shamanism", "seed-energy-process", "blog",
}
ASSET_PREFIXES = ("images/", "../images/", "preview-redesign/", "../preview-redesign/")
ASSET_FILES = {"shared.css", "shared.js", "../shared.css", "../shared.js",
               "analytics.js", "../analytics.js"}


def url_path(rel):
    """_src-relative html filename -> clean URL path (no .html, index collapses)."""
    rel = rel.replace("\\", "/")
    if rel.endswith("index.html"):
        rel = rel[:-len("index.html")]      # blog/index.html -> 'blog/', index.html -> ''
    elif rel.endswith(".html"):
        rel = rel[:-5]
    return rel


def lang_url(path, lang, absolute=True):
    prefix = "" if lang == DEFAULT_LANG else f"{lang}/"
    base = f"{SITE}/" if absolute else "/"
    return f"{base}{prefix}{path}"


def out_path(rel, lang):
    rel = rel.replace("\\", "/")
    if lang == DEFAULT_LANG:
        return os.path.join(ROOT, rel)
    return os.path.join(ROOT, lang, rel)


def text_of(data_html):
    """Strip tags from a data-* HTML value -> plain text (for <title>, meta)."""
    t = BeautifulSoup(data_html or "", "html.parser").get_text(" ", strip=True)
    t = re.sub(r"\s+([.,;:!?»)])", r"\1", t)   # drop space before punctuation
    t = re.sub(r"\s{2,}", " ", t).strip()
    return t


def truncate(s, n=158):
    s = re.sub(r"\s+", " ", s).strip()
    if len(s) <= n:
        return s
    cut = s[:n].rsplit(" ", 1)[0]
    return cut.rstrip(" ,.;:—-") + "…"


def derive_meta(soup, lang, existing_title, existing_desc, is_home=False):
    """Per-language <title> + description. EN reuses the existing (already
    English) hand-crafted meta on modality/blog pages; IT/PT always derive from
    the H1 + hero lede data-{lang}. The homepage's existing meta is Italian, so
    EN is derived there too (is_home) rather than reused."""
    h1 = soup.find("h1")
    lede = soup.select_one(".tagline, .lede, .article-hero .lede, "
                           ".page-hero p, .article-hero p, .hero-content p, "
                           ".hero p, .hero-subtitle, header p")
    title = existing_title
    desc = existing_desc
    # TITLE: EN reuses the hand-crafted existing <title> (good English on
    # modality/blog pages); IT/PT — and the homepage's EN — derive from the H1.
    if (lang != "en" or is_home) and h1 is not None:
        t = text_of(h1.get(f"data-{lang}"))
        if t:
            title = f"{t} | {BRAND}"
    # DESCRIPTION: always derive from the hero lede's data-{lang}. The source
    # <meta description> is inconsistent (often Italian even on English pages),
    # so reusing it would mix languages. Fall back to existing only if no lede.
    if lede is not None:
        d = text_of(lede.get(f"data-{lang}"))
        if d:
            desc = truncate(d)
    return title, desc


def bake_language(soup, lang):
    """Replicate setLang(lang) statically, then strip the data-* attributes."""
    for el in soup.select("[data-en]"):
        val = el.get(f"data-{lang}")
        if val is not None and val != "":
            tag = el.name.lower()
            if tag in ("input", "textarea"):
                el["placeholder"] = text_of(val)
            elif tag == "option":
                el.string = text_of(val)
            else:
                el.clear()
                # snapshot the fragment's nodes BEFORE appending — append() pops
                # each node from the fragment, so iterating live .contents skips.
                frag_nodes = list(BeautifulSoup(val, "html.parser").contents)
                for node in frag_nodes:
                    el.append(node)
        # strip translation attributes from the baked output
        for a in ("data-en", "data-it", "data-pt"):
            if a in el.attrs:
                del el[a]


def set_meta(soup, name=None, prop=None, content=None):
    sel = f'meta[name="{name}"]' if name else f'meta[property="{prop}"]'
    tag = soup.select_one(sel)
    if tag is None:
        return
    tag["content"] = content


def rewrite_head(soup, rel, lang):
    path = url_path(rel)
    canon = lang_url(path, lang)
    # title / description
    title_tag = soup.find("title")
    existing_title = title_tag.get_text() if title_tag else BRAND
    desc_tag = soup.select_one('meta[name="description"]')
    existing_desc = desc_tag["content"] if desc_tag and desc_tag.has_attr("content") else ""
    is_home = os.path.basename(rel) == "index.html"
    title, desc = derive_meta(soup, lang, existing_title, existing_desc, is_home)
    if title_tag:
        title_tag.string = title
    set_meta(soup, name="description", content=desc)
    set_meta(soup, prop="og:title", content=title)
    set_meta(soup, prop="og:description", content=desc)
    set_meta(soup, prop="twitter:title", content=title)
    set_meta(soup, prop="twitter:description", content=desc)
    set_meta(soup, prop="og:url", content=canon)
    set_meta(soup, prop="twitter:url", content=canon)
    set_meta(soup, prop="og:locale", content=LOCALE[lang])
    # remove alternate-locale lines (hreflang covers this)
    for m in soup.select('meta[property="og:locale:alternate"]'):
        m.decompose()

    # canonical
    can = soup.select_one('link[rel="canonical"]')
    if can:
        can["href"] = canon
    # hreflang: drop existing, rebuild
    for a in soup.select('link[rel="alternate"][hreflang]'):
        a.decompose()
    head = soup.head
    anchor = can or head
    for code, l in (("it", "it"), ("en", "en"), ("pt", "pt"),
                    ("x-default", DEFAULT_LANG)):
        link = soup.new_tag("link", rel="alternate")
        link["hreflang"] = code
        link["href"] = lang_url(path, l)
        anchor.insert_after(link)
        anchor = link

    # <html lang>
    soup.html["lang"] = lang

    # inject window.HU_LANG before anything else in <head> so shared.js sees it
    flag = soup.new_tag("script")
    flag.string = f"window.HU_LANG='{lang}';"
    head.insert(0, flag)


def convert_toggle(soup, rel):
    """EN/IT/PT buttons -> real links to this page in each language."""
    path = url_path(rel)
    mapping = {"langIt": "it", "langEn": "en", "langPt": "pt"}
    for el_id, l in mapping.items():
        btn = soup.find(id=el_id)
        if btn is None:
            continue
        a = soup.new_tag("a", href=lang_url(path, l, absolute=False))
        a["id"] = el_id
        a["class"] = btn.get("class", [])
        if btn.has_attr("aria-label"):
            a["aria-label"] = btn["aria-label"]
        a.string = btn.get_text()
        btn.replace_with(a)
    # mark the active language
    active = {"it": "langIt", "en": "langEn", "pt": "langPt"}
    return active


def is_internal_page_link(href):
    if not href:
        return None
    if href.startswith(("#", "mailto:", "tel:", "javascript:")):
        return None
    # full-URL internal
    m = re.match(r"^https?://holisticunity\.app/(.*)$", href)
    if m:
        return m.group(1)
    # external host
    if re.match(r"^https?://", href):
        return None
    # asset
    if href.lstrip("./").startswith(("images/", "preview-redesign/")) or \
       href.lstrip("/").split("?")[0] in {"shared.css", "shared.js", "analytics.js"}:
        return None
    # leading-slash internal
    if href.startswith("/"):
        return href.lstrip("/")
    # relative internal page (e.g. "astrology", "blog/x", "../reiki")
    return href.lstrip("./")


def slug_root(path):
    """First path segment, to test against PAGE_SLUGS."""
    return path.split("/")[0].split("#")[0].split("?")[0]


def rewrite_links_for_subdir(soup, lang):
    """In /en and /pt trees, make every internal PAGE link an absolute
    /{lang}/... path. Relative asset paths are absolutized separately."""
    for a in soup.find_all("a", href=True):
        href = a["href"]
        inner = is_internal_page_link(href)
        if inner is None:
            continue
        if slug_root(inner) not in PAGE_SLUGS:
            continue
        # preserve any #fragment
        a["href"] = f"/{lang}/{inner}" if inner else f"/{lang}/"


def absolutize_assets(soup):
    """Relative css/js/image refs -> root-absolute so subfolder pages resolve."""
    def fix(val):
        if val is None:
            return None
        v = val
        v = re.sub(r'^(?:\.\./)+', '/', v)          # ../images/x -> /images/x
        if v.startswith(("images/", "preview-redesign/", "shared.css",
                         "shared.js", "analytics.js")):
            v = "/" + v
        return v

    for tag in soup.find_all(src=True):
        tag["src"] = fix(tag["src"])
    for tag in soup.find_all(href=True):
        # only rewrite asset hrefs (stylesheet / icon), never page links
        rels = tag.get("rel", [])
        if tag.name == "link" and any(r in ("stylesheet", "icon", "apple-touch-icon", "preload") for r in rels):
            tag["href"] = fix(tag["href"])
    for tag in soup.find_all(srcset=True):
        tag["srcset"] = fix(tag["srcset"])


def extract_faq(soup):
    """Pull (question, answer) pairs from the baked visible FAQ accordion."""
    qa = []
    for item in soup.select(".faq-item"):
        qel = item.select_one(".faq-question")
        ael = item.select_one(".faq-answer")
        if not qel or not ael:
            continue
        spans = qel.find_all("span", recursive=False)
        q = next((s.get_text(" ", strip=True) for s in spans
                  if "faq-icon" not in (s.get("class") or [])),
                 qel.get_text(" ", strip=True))
        a = ael.get_text(" ", strip=True)
        if q and a:
            qa.append((q, a))
    return qa


def localize_jsonld(soup, lang):
    """Make structured data match the page language: rebuild FAQPage from the
    baked visible FAQ, add inLanguage, and sync description on content types."""
    desc_tag = soup.select_one('meta[name="description"]')
    desc = desc_tag["content"] if desc_tag and desc_tag.has_attr("content") else None
    DESC_TYPES = {"Service", "BlogPosting", "Article", "Product",
                  "WebPage", "MobileApplication"}
    for script in soup.find_all("script", attrs={"type": "application/ld+json"}):
        raw = script.string or script.get_text()
        try:
            data = json.loads(raw)
        except Exception:
            continue
        objs = data if isinstance(data, list) else [data]
        for obj in objs:
            if not isinstance(obj, dict):
                continue
            obj["inLanguage"] = lang
            t = obj.get("@type")
            if t == "FAQPage":
                qa = extract_faq(soup)
                if qa:
                    obj["mainEntity"] = [
                        {"@type": "Question", "name": q,
                         "acceptedAnswer": {"@type": "Answer", "text": a}}
                        for q, a in qa
                    ]
            elif t in DESC_TYPES and desc:
                obj["description"] = desc
        script.string = json.dumps(data, ensure_ascii=False, indent=2)


def build_page(rel):
    src_file = os.path.join(SRC, rel)
    with open(src_file, "r", encoding="utf-8") as fh:
        raw = fh.read()
    for lang in LANGS:
        soup = BeautifulSoup(raw, "html.parser")
        # rewrite_head + convert_toggle read data-* (title/desc, H1) and so must
        # run BEFORE bake_language strips those attributes.
        rewrite_head(soup, rel, lang)
        active = convert_toggle(soup, rel)
        bake_language(soup, lang)
        localize_jsonld(soup, lang)   # after bake: visible FAQ is now in `lang`
        if lang != DEFAULT_LANG:
            rewrite_links_for_subdir(soup, lang)
            absolutize_assets(soup)
        # mark active toggle (after potential link rewrite)
        for code in LANGS:
            el = soup.find(id={"it": "langIt", "en": "langEn", "pt": "langPt"}[code])
            if el is not None:
                classes = [c for c in el.get("class", []) if c != "active"]
                if code == lang:
                    classes.append("active")
                    el["aria-current"] = "page"   # a11y: current language
                elif el.has_attr("aria-current"):
                    del el["aria-current"]
                if classes:
                    el["class"] = classes
                elif el.has_attr("class"):
                    del el["class"]               # avoid empty class=""
        html = str(soup)
        if not html.lstrip().startswith("<!DOCTYPE"):
            html = "<!DOCTYPE html>\n" + html
        html = html.replace("<head>", "<head>\n" + GEN_HEADER, 1)
        dest = out_path(rel, lang)
        os.makedirs(os.path.dirname(dest) or ".", exist_ok=True)
        with open(dest, "w", encoding="utf-8", newline="") as fh:
            fh.write(html)


def main():
    rels = []
    for f in glob.glob(os.path.join(SRC, "*.html")) + glob.glob(os.path.join(SRC, "blog", "*.html")):
        rels.append(os.path.relpath(f, SRC).replace("\\", "/"))
    rels.sort()
    if ONLY:
        rels = [r for r in rels if os.path.splitext(os.path.basename(r))[0] == ONLY]
    for rel in rels:
        build_page(rel)
        print(f"  built {rel:42} -> {url_path(rel) or '/'} , /en/… , /pt/…")
    print(f"\nGenerated {len(rels)} pages × {len(LANGS)} languages = {len(rels)*len(LANGS)} files")


if __name__ == "__main__":
    main()
